### ISSUE TITLE
AssertionError: Expected to find a version within 'alpha'

### ISSUE THREAD

**Issue by sourcefrog** [Byron/google-apis-rs#126]
In e4f89ce0c6c16480cccbe92aeaad55e3811beb83:

```
% make regen-apis
PYTHONPATH=src/mako/lib .pyenv-Linux/bin/python etc/bin/mako-render --template-dir '.' -io src/mako/deps.mako=.cli.deps --data-files etc/api/shared.yaml etc/api/type-cli.yaml etc/api/api-list.yaml
Traceback (most recent call last):
  File "etc/bin/mako-render", line 324, in cmdline
    result = post_processor(template.render(**data_converted), output_file)
  File "/home/mbp/src/google-apis-rs/.pyenv-Linux/local/lib/python2.7/site-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/mbp/src/google-apis-rs/.pyenv-Linux/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/mbp/src/google-apis-rs/.pyenv-Linux/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/mbp/src/google-apis-rs/.pyenv-Linux/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "src/mako/deps.mako", line 48, in render_body
    <%
  File "/home/mbp/src/google-apis-rs/src/mako/lib/util.py", line 809, in library_name
    version = to_api_version(version)
  File "/home/mbp/src/google-apis-rs/src/mako/lib/util.py", line 786, in to_api_version
    assert m, "Expected to find a version within '%s'" % v
AssertionError: Expected to find a version within 'alpha'
Makefile:70: recipe for target '.cli.deps' failed
make: *** [.cli.deps] Error 1
```

I guess there's an API that now just says its version is 'alpha' and this is unexpected?

**Comment by sourcefrog** [comment]
Ah perhaps this is due to the apis 'vm_beta' and 'vm_alpha' and it thinks the initial v is the start of a version number.

**Comment by Byron** [comment]
Thanks for letting me know ! The respective method has been adjusted to deal with these special version names too. I wished at some point google would name their versions consistently ... semantic versions go, go, go ;).

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/AZ9Nzp8GowE).

*`Google.rs #47 [handle special version names]`*

[\![thumb](https://i.ytimg.com/vi/AZ9Nzp8GowE/mqdefault.jpg)](https://youtu.be/AZ9Nzp8GowE)

**Comment by sourcefrog** [comment]
Thanks for fixing this. I'm currently unable to build the tree and test this due to #131.

**Comment by Byron** [comment]
Building should be fine now.
I am closing the issue as it was fixed a while ago.
